# docker-compose.yml
version: '3.7'
services:

  db:
    image: mysql:8
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - net
  gotrue:
    image: ghcr.io/heigvd-software-engineering/gotrue
    container_name: gotrue
    env_file:
      - .env
    networks:
      - net
    ports:
      - "8082:9999"
  app:
    image: cosmtrek/air
    container_name: app
    env_file:
      - .env
    networks:
      - net
    ports:
      - "3000:3000"
    working_dir: /go/src/github.com/cosmtrek/hub
    volumes:
      - ".:/go/src/github.com/cosmtrek/hub"

volumes:
  db_data:
networks:
  net:
    external: false  