# docker-compose.yml
version: '3.7'
services:
  db:
    image: postgis/postgis
    container_name: db
    environment:
      - POSTGRES_DB=contextual-guide
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - net
  gotrue:
    image: ghcr.io/heigvd-software-engineering/gotrue
    container_name: gotrue
    env_file:
      - .gotrue.env
    networks:
      - net
    ports:
      - "8082:9999"
  app:
    image: cosmtrek/air
    container_name: app
    env_file:
      - .app.env
    networks:
      - net
    ports:
      - "3000:3000"
    working_dir: /go/src/github.com/cosmtrek/hub
    volumes:
      - ".:/go/src/github.com/cosmtrek/hub"
  swagger:
    image: quay.io/goswagger/swagger
    container_name: swagger
    environment:
      - GOPATH=/go
    volumes:
      - ".:/go/src"
    working_dir: /go/src
    command: ["serve", "swagger.json", "--port", "4000", "--no-open"]
    ports:
      - "4000:4000"

volumes:
  data:

networks:
  net:
    external: false  