apiVersion: v1
kind: Service
metadata:
  labels:
    component: gotrue-service
    app: contextual-guide
  name: gotrue-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: gotrue
  selector:
    component: gotrue
    app: contextual-guide
  type: LoadBalancer
