apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: contextual-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgis-db
      app: contextual-guide
  template:
    metadata:
      labels:
        app: contextual-guide
        component: postgis-db
    spec:
      containers:
        - name: postgis
          image: postgis/postgis:12-2.5-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgis-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgisdata
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: postgisdata
