kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgis-pv-volume
  labels:
    type: local
    app: postgis
  namespace: contextual-guide
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgis-pv-claim
  namespace: contextual-guide
  labels:
    app: postgis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
