apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgis-db-service
    app: contextual-guide
  name: postgis-db-service
  namespace: contextual-guide
spec:
  ports:
    - name: postgis
      port: 5432
      targetPort: 5432
  selector:
    component: postgis-db
    app: contextual-guide
  type: LoadBalancer
