apiVersion: v1
kind: Service
metadata:
  labels:
    component: tile38
    tile38: contextual-guide
  name: tile38
spec:
  ports:
    - port: 80
      targetPort: 9851
      name: tile38
  selector:
    component: tile38
    tile38: contextual-guide
  type: LoadBalancer
