name: Contextual Guide - CD to docker Hub
on:
  push:
    branches:  ['master']
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go test ./...
  release-docker:
    name: Release on DockerHub
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Build docker image
        run: |
          TAG_NAME=$(echo ${GITHUB_REF:10})
          docker build --cache-from ghcr.io/heigvd-software-engineering/contextual-guide:latest -t ghcr.io/heigvd-software-engineering/contextual-guide:latest .
          docker push ghcr.io/heigvd-software-engineering/contextual-guide:latest
