name: Contextual Guide - CD to docker Hub
on:
  push:
    tags: ['*']
jobs:
  release-docker:
    name: Release on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Build docker image
        run: |
          TAG_NAME=$(echo ${GITHUB_REF:10})
          docker build --cache-from ghcr.io/heigvd-software-engineering/contextual-guide:latest -t ghcr.io/heigvd-software-engineering/contextual-guide:latest -t ghcr.io/heigvd-software-engineering/contextual-guide:$TAG_NAME .
          docker push ghcr.io/heigvd-software-engineering/contextual-guide:$TAG_NAME
