name: Contextual Guide - CD to docker Hub
on:
  push:
    tags: ['*']
jobs:
  release-docker:
    name: Release on DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build docker image
        run: |
          TAG_NAME=$(echo ${GITHUB_REF:10})
          docker build --cache-from flatrome/contextual-guide:latest -t flatrome/contextual-guide:latest -t flatrome/contextual-guide:$TAG_NAME
          docker push flatrome/contextual-guide:TAG_NAME
